### PR TITLE
Fix `kk` to `jk`

### PR DESCRIPTION
**Pull request by sweetliquid**
Fix a typo, merge it please.

### CODE REVIEW

**Review by Shatur95 — APPROVED** [review]

**Comment by theol0403** [comment]
This should not have been merged. Have you tested this?
The way the composite escape works is slightly confusing, but it basically allows for the following combos:
- AA
- AB

so
```
    {
        "command": "vscode-neovim.compositeEscape1",
        "key": "j",
        "when": "neovim.mode == insert && editorTextFocus",
        "args": "j"
    },
    {
        "command": "vscode-neovim.compositeEscape2",
        "key": "k",
        "when": "neovim.mode == insert && editorTextFocus",
        "args": "k"
    }
```
Allows for jj and jk to escape. 
However, with this merge, it causes when you press j to type k instead, breaking all combinations and only allowing you to type k with both j and k.

**Comment by Shatur95** [comment]
Did not know, sorry. @sweetliquid, could you undo this change?

**Comment by theol0403** [comment]
All good, maybe for the future we should let PRs sit for a bit before merging :p

**Comment by Shatur95** [comment]
Yes, just thought it was a small typo: D

**Comment by theol0403** [comment]
On the other hand, that's one down for Octoberfest! :rofl:

**Comment by Shatur95** [comment]
No, this PR will not count unless the repo contains the topic "hacktoberfest" or the PR is marked as "hacktoberfest-accept" :(

**Comment by sweetliquid** [comment]
Sorry, but I still haven't figured it out yet. Orz

**Pull request merged**
