### PR TITLE
Use latest cursor position from neovim rather than vscode to calculate cursor movement diff

### LINKED ISSUE #495: My cursor is on speed, often leaves VS Code behind.
As you may have noticed in some of my recordings, my cursor is :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :shopping_cart:.

I some times move too fast, and VS Code rendering will not be up to date. Or sometimes, VS Code's cursor will have moved further than mine. Maybe this happens once it has been slammed with all the previous movement, and then VS Code handles the input instead of neovim? I think that may be the case, because sometimes in insert mode I'll type some stuff, then ctrl+c and start moving with `j`, but instead I'll see `jjjjjj` inputted into the text.

I think this is also more likely to happen when other things are taking up CPU, so that it slows both VS Code and Neovim down.

I noticed the `Vim` plugin also has the same issue.

### PR DESCRIPTION
**Pull request by asvetliakov**
Fixes #495 

Ops, totally broken

### CODE REVIEW

**Comment by jvbianchi** [comment]
I just tried this version, the cursor does not move.

**Comment by asvetliakov** [comment]
Yep, let me adjust the PR

**Comment by jvbianchi** [comment]
After this fix, it seems to be working fine.

**Comment by asvetliakov** [comment]
Unfortunately there are many difficulties with this approach. I need to find different way

**Pull request closed without merging**
