### PR TITLE
Fix 344

### LINKED ISSUE #344: Cursor move delay on change command
*Originally posted [here](https://github.com/asvetliakov/vscode-neovim/pull/334#issuecomment-687538718)*
> Sometimes, when I go into insert mode with something that modifies the buffer length (ie change commands) and start typing too fast, the cursor does not update fast enough and it inserts text in the wrong place. 
> For example, here I type `ciwadditional` but this happens:
> Peek 2020-09-04 20-14
> I am on the latest commit of this branch.

This problem still happens with an empty init.vim and all vscode extensions disabled.
Here, you can see the first time it ignores the "j", and the second time it places "j" in the wrong spot after the cursor. I have slowed the gif down by 50%.

ezgif-4-441c936d1ae6

Edit:
The more vscode plugins I have enabled, the worse the issue becomes. With all extensions disabled like above, the issue only happens 30% of the time, and usually with only one or two characters. With all extensions enabled, the issue becomes as bad as in the first screenshot.

### PR DESCRIPTION
**Pull request by asvetliakov**
Fix #344

### CODE REVIEW

**Comment by asvetliakov** [comment]
@ theol0403 🔔  please try

**Comment by theol0403** [comment]
It looks like it has solved the problem! It now does not mess up the order of characters.
However, it still does have the little cursor jump, which I don't think happened on 0.0.52
This PR:
Peek 2020-09-06 16-49
0.0.52:
Peek 2020-09-06 16-53

**Comment by asvetliakov** [comment]
@theol0403 Can you enable logging and upload it somewhere ? Also perhaps you should revisit your installed extensions the change document lag is very bad

**Comment by theol0403** [comment]
Sure, will do. I think the lag is mostly due to clangd semantic highlighting, not sure.

**Comment by theol0403** [comment]
Sorry, I'm not quite sure how to debug :confused: .
I put this in my settings but I'm not seeing the log file written.
```
  "vscode-neovim.logPath": "/home/theol/vscode.log",
  "vscode-neovim.logLevel": "debug",
```

**Comment by asvetliakov** [comment]
did you restart the editor?

**Comment by theol0403** [comment]
Yes, many times, but for some reason I restarted it again and the file showed up :shrug:

**Comment by theol0403** [comment]
https://pastebin.com/XL4eWj0D

This is me opening the editor, moving right a few characters, and then `ciw`, then escape, undo, and save.

**Comment by asvetliakov** [comment]
thank you, can you pull and recompile latest commit from this branch ? i'd like to look into log timestamps as well (just added)

**Comment by theol0403** [comment]
Oops, sorry yeah I thought I pulled but I guess I got distracted while it was building.

**Comment by theol0403** [comment]
https://pastebin.com/FBdbK0gw

On the latest commit, for some reason this happens:

Peek 2020-09-06 17-58

**Comment by asvetliakov** [comment]
From the logs:
1. It looks a change in neovim buffers trigger many related changes in other buffers. You should revisit your init.vim and disable things which don't make sense with vscode.

2. Something is EATING extension host on vscode side
```
start->
2020-09-07T00:57:07.955Z DocumentChangeManager: Applying edits for file:///home/theol/Documents/github/lib7842/include/lib7842/api/positioning/spline/stepper.hpp

change draw, extension host was blocked from this time->
2020-09-07T00:57:08.030Z DocumentChangeManager: Change text document for uri: file:///home/theol/Documents/github/lib7842/include/lib7842/api/positioning/spline/stepper.hpp

Extension host was unblocked->
2020-09-07T00:57:08.783Z DocumentChangeManager: Skipping a change since versions equals
2020-09-07T00:57:08.786Z BufferManager: Received onDidChangeEditorOptions
2020-09-07T00:57:08.786Z BufferManager: Received onDidChangeEditorOptions
2020-09-07T00:57:08.866Z DocumentChangeManager: Changes succesfully applied for file:///home/theol/Documents/github/lib7842/include/lib7842/api/positioning/spline/stepper.hpp
```

Paste your extension list here

**Comment by theol0403** [comment]
1. humm, I do keep my init.vim as clean as possible (there isn't anything in there that does not make sense for vscode, but I can check again). I'll check if the delay happens with empty init.vim.
2. 
```
asvetliakov.vscode-neovim
CoenraadS.bracket-pair-colorizer-2
cschlosser.doxdocgen
eamodio.gitlens
emilast.LogFileHighlighter
esbenp.prettier-vscode
James-Yu.latex-workshop
jeff-hykin.better-cpp-syntax
kevinkyang.auto-comment-blocks
llvm-vs-code-extensions.vscode-clangd
matklad.rust-analyzer
monokai.theme-monokai-pro-vscode
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-vscode-remote.remote-containers
ms-vscode.cpptools
ms-vscode.vscode-typescript-tslint-plugin
ms-vsonline.vsonline
npxms.hide-gitignored
pascalsenn.keyboard-quickfix
ryzngard.vscode-header-source
streetsidesoftware.code-spell-checker
svipas.code-autocomplete
twxs.cmake
usernamehw.errorlens
WakaTime.vscode-wakatime
XadillaX.viml
```

The heaviest plugin I can think of is `svipas.code-autocomplete` (tabnine fork) and of course the C++ plugins (clangd, jeff-hykin.better-cpp-syntax).

**Comment by theol0403** [comment]
The problem happens with empty init.vim. 
I'll try disabling extensions until it speeds up.
However, as I show in the screenshots above, I had the exact same vscode configuration in 0.0.52 but it worked much faster.

**Comment by theol0403** [comment]
Huh, I just found the culprit: `CoenraadS.bracket-pair-colorizer-2`. Now vscode is much faster.

**Comment by asvetliakov** [comment]
can you record a perf profile ? i'll try to find the culprit.

`0.0.52` faster because it worked differently. It wasn't waiting for change operations and produced various cursor jump/positions problems.

**Comment by theol0403** [comment]
Updated log with init.vim and bracket-pair-colorizer disabled: https://pastebin.com/iAvYfyjf

**Comment by asvetliakov** [comment]
Yeah i see
```
apply->
2020-09-07T01:41:40.282Z DocumentChangeManager: Applying edits for file:///home/theol/Documents/github/lib7842/include/lib7842/api/positioning/spline/stepper.hpp

applied, draw->
2020-09-07T01:41:40.292Z DocumentChangeManager: Change text document for uri: file:///home/theol/Documents/github/lib7842/include/lib7842/api/positioning/spline/stepper.hpp

unblock, update cursor->
2020-09-07T01:41:40.293Z DocumentChangeManager: Changes succesfully applied for file:///home/theol/Documents/github/lib7842/include/lib7842/api/positioning/spline/stepper.hpp
2020-09-07T01:41:40.294Z TypingManager: Waiting done, disposing type handler
```

10ms instead of 800!

**Comment by asvetliakov** [comment]
For reference see [this](https://github.com/microsoft/vscode/issues/75627) and [this](https://github.com/microsoft/vscode/issues/65876). Go and upvote, doesn't seem to help though 🤣

**Comment by theol0403** [comment]
Wow, vscode is so much more responsive :joy: 
Well, I think this can be merged then, it is no longer messing up the input and it is now visually fast as well.
Thanks so much for your time and fixing this issue!

PS: while debugging this I came across some buffer desyncs and cursor jumps. I'll make an issue if I can repro, but just wanted to let you know in case you have an idea of what it is. There is a chance it is from my init.vim as well.

**Comment by asvetliakov** [comment]
>PS: while debugging this I came across one or two buffer desyncs and cursor jumps. I'll make an issue if I can repro, but just wanted to let you know in case you have an idea of what it is. There is a chance it is from my init.vim as well.

For buffer desync there is one known upstream issue - #116 . the `}` here doesn't exist in vim buffer however being sent to vscode. Can be something related. If you find non related repro - let me know, i'm trying to look into such issues asap

**Comment by asvetliakov** [comment]
Thank you for your help with testing btw!

**Pull request merged**
