### PR TITLE
Fixing tabs

### LINKED ISSUE #239: cursor is in the wrong place in tab-indent file
1. 4-space-indent file,ujhk move cursor right.
2. after change all space to tab,ujhk movement is chaos,can't reach the head of line with ^ or h,can't search the right words under the cursor, etc...

### LINKED ISSUE #275: tab width counted as 1 in visual block mode
```
abcdefghijklmn
    123456
```
The second line starts with a tab of width 4.
Now move the cursor to `e`, press `ctrl-v`, press `j`.
The cursor jumps to '4' instead of '1'.
Screenshot_2020-05-28_00-30-13

### PR DESCRIPTION
**Pull request by jhgarner**
This fixes #275 by matching the tabwidth that vscode and vim use. I think this also fixes #239 and #264 and any other issues about cursor movement in tabbed files.

### CODE REVIEW

**Comment by jhgarner** [comment]
It looks like I accidentally included the easymotion changes here as well. If that's a problem, I'll look into what I need to do to fix the history.

**Comment by theol0403** [comment]
I haven't verified for sure that this PR caused it, but after installing this PR, highlighting seems really messed up. I don't have a screenshot to show simply because the highlighting is barely visible (in visual-line for example). 

If you aren't having the same problem, I can try to investigate and provide more information.

**Comment by jhgarner** [comment]
Thanks for pointing that out. I tested highlighting with visual block mode but managed to miss that the other visual modes had gotten messed up. I'll investigate why and update this code.

**Comment by theol0403** [comment]
Cool, glad it's not just me =).
It seems to not just be the other visual modes, it's anything that requires highlighting of a whole line or more. For example, I have the vim-highlightedyank plugin installed, and it does not work when yanking anything over one line.

**Comment by jhgarner** [comment]
Any highlight that tried to go beyond the end of a line was broken because I thought indexing an array past the end would return undefined, not null. Hopefully that's fixed now.

**Comment by theol0403** [comment]
Sweet! Just tried it out and it works great. This whole PR has the added benefit that it highlights regions more like nvim, where it won't highlight empty lines and only highlights to the end of the line.

Thanks a ton for making these PRs, it really makes this plugin even more enjoyable to use :slightly_smiling_face: .

**Comment by Shatur95** [comment]
Thank you, switched to this branch currently.

**Comment by Shatur95** [comment]
I'm not sure if this is related to the PR, but do you faced with line desync? Sometimes I use `dd` and this removes previous line instead of current.

**Comment by jhgarner** [comment]
I haven't seen any line desyncs. Are there any files and/or particular actions that lead to it?

**Comment by Shatur95** [comment]
I would like to provide steps to reproduce, but this happens randomly :(
Maybe this because of plugins, but I use [only basic](https://github.com/Shatur95/neovim-config/tree/master/pack/plugins/start).
So, the plugin works perfectly for you?

**Comment by jhgarner** [comment]
No, I haven't seen that issue although there's a lot of internal state and it's very likely I've missed some edge cases. Do the desyncs only happen in files with hard tabs?

**Comment by Shatur95** [comment]
Sorry for a long reply. This was hard to reproduce, but now I have 100% reproducible steps:

```vim
dd
<Up>
u
<Up>
dd
u
<Down>
dd
```

On last step you will remove upper line instead of current. But I seems to not related to the PR, the issue reproducible on latest master too for me. Can you reproduce it on your side?

**Comment by jhgarner** [comment]
Thanks! I just checked and I can also reproduce the highlighting issue following your steps. As for the desync, It doesn't seem to happen for me. I even followed the install instructions for the link you shared above with your config and it still worked as expected. Any chance you can share the file you tested this in? I've run into one desync randomly while editing a file so far which seemed similar to what you're describing but after refreshing, I couldn't reproduce it.

**Comment by Shatur95** [comment]
> Thanks! I just checked and I can also reproduce the highlighting issue following your steps.

Thanks for the checking!

> It doesn't seem to happen for me. I even followed the install instructions for the link you shared above with your config and it still worked as expected. Any chance you can share the file you tested this in? I've run into one desync randomly while editing a file so far which seemed similar to what you're describing but after refreshing, I couldn't reproduce it.

Sorry, I just double checked and found that I provided a bit wrong steps. The following should reproduce the bug:

```vim
dd
gk
u
gk
dd
u
gj
dd
```

I discovered it because I have mapped `j` to `gj`, `k` to `jk` (for navigation between soft-wrapped lines)

**Comment by jhgarner** [comment]
With those instructions I can reproduce it with a blank nvim config. It seems like it only happens on longer lines which makes me think something is going wrong with text wrapping. Since you said it's broken on master as well, it might be worth opening your own issue for this.

**Comment by Shatur95** [comment]
Thanks! Just opened #312. I would try to fix this problem, but I'm not familiar with TypeScript :(
So, I hope that someone will be interested in fixing it.

**Comment by asvetliakov** [comment]
Superseded by #334. Thank you for the PR!

**Pull request closed without merging**
